version: "3.8"

services:
  app:
    build: . # Assuming your Dockerfile is in the same directory
    container_name: my-node-container # Optional: Specify a custom container name
    ports:
      - "8080:8080" # Maps port 8080 of the container to port 8080 on the host
    env_file:
      - ./backend/.env # Specifies the .env file to use
